* Experimental Evaluation

This repository stores all the experiments code. For making the experiments accurate, we proposed a possible real system requirement list detailed as follows.

** Hypothetical System - Sensor over the Internet
 This section lists the system's requirements used in *Section - Experimental Evaluation*. We provided an example of code that explores different aspects of embedded systems coding. Let us consider the systems has three sensors, network access, Flash access, and has to monitor and make some calculation with the value of the sensors. The following sections detail the features needed. 

*** Requirement - R01
   It should capture samples of 3 different sensors A (1 byte), B (1 byte) and C (4 bytes) every three seconds;

*** Requirement  - R02
	 It must store, in RAM (volatile), the last ten sensors' samples;

*** Requirement  - R03
	It can receive remote requests of six different types:
	 1. *0xa0* - It requests Sensor A data;
	 2. *0xa1* - It requests Sensor B data;
	 3. *0xa2* - It requests Sensor C data;
	 4. *0xa3* - It requests last ten samples Sensor A data mean;
	 5. *0xa4* - It requests last ten samples Sensor B data mean;
	 6. *0xa5* - It requests last ten samples Sensor C data mean;

*** Requirement - R04
  It must store, in Flash (non-volatile), the last sample of sensor A and the last remote response data every 30 seconds. When the system starts, it must recover the flash data;

*** Requirement - R05
  The system receives a random remote request every 30 seconds.

** Implementations
 We implemented three variations of the same hypothetical system. The first tries to mimic the [[https://www.arduino.cc/][Arduino]] way to code (Single-threaded setup/loop); the second employs only RTOS features (Multi-threaded); the last one uses Zeta (Multi-threaded with Zeta).

*** Single-threaded implementation
  This one follows the Arduino implementation approach based on a single thread with all the responsibilities. It this case there is only two separations of code the Setup portions, which implements all the declaration and configuration of the module; and the Loop portion where the code executes.

*** Multi-threaded implementation
  On this implementation, we tried to use acceptable programming practices separating the system's functionality into four modules. The first one is the BOARD responsible for capturing the sensors' samples. The CORE is the central module capable of storing the volatile data, calculate the mean and for responding to remote requests. There is the STORAGE module aimed to store the non-volatile data and restore it when the system starts. The last one is NET able to receive requests and send responses to the remote peer. We tried to keep it simple and used only queues and semaphores.

*** Zeta implementation
  This one is similar to the Multi-threaded implementation in terms of module separation. However, all communication and storage functionality is Zeta responsibility. Consequently, there are only BOARD, CORE, and NET modules whenever the middleware assumes the STORAGE's role.

*** Execution

	Clone this repository to the zephyrproject folder. 

	#+BEGIN_SRC bash
cd /home/.../zephyrproject
git clone <this repository url> 
	#+END_SRC

	Before compiling the samples you have to make sure the env for Zephyr is ok. Execute the following command:

	#+BEGIN_SRC bash
source ${ZEPHYR_BASE}/zephyr-env.sh 
	#+END_SRC

	For calculating the memory footprint for this sample, we have to execute the following commands to build the project to the nrf52840dongle board. For illustration we are compiling the zeta variation.
   
	#+BEGIN_SRC bash
cd sensor-over-internet-zeta
CONF_FILE=prj_nrf52840dongle_nrf52840.conf; rm -rf build && west build -b nrf52840dongle_nrf52840
	#+END_SRC

#+begin_example
-- west build: generating a build system
[ZETA]: Running zeta.cmake
[ZETA]: Current dir = /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-zeta
[ZETA]: ZETA_MODULE_DIR = /home/.../.local/lib/python3.6/site-packages/zeta
[ZETA]: PROJECT_DIR = /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-zeta/build
[ZETA]: ZETA_DIR =  /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-zeta/build/zeta
[ZETA]: ZETA_SRC_DIR = /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-zeta/build/zeta/src
[ZETA]: ZETA_INCLUDE_DIR = /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-zeta/build/zeta/include
[ZETA]: ZETA_TEMPLATES_DIR = /home/.../.local/lib/python3.6/site-packages/zeta/templates
[ZETA]: Creating Zeta project folder
[ZETA]: Generating zeta.h...[OK]
[ZETA]: Generating zeta.c...[OK]
[ZETA]: Generating zeta.conf...[OK]
Including boilerplate (Zephyr base): /home/.../zephyrproject/zephyr/cmake/app/boilerplate.cmake
-- Application: /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-zeta
-- Zephyr version: 2.3.0-rc1 (/home/.../zephyrproject/zephyr)
-- Found Python3: /usr/bin/python3.6 (found suitable exact version "3.6.9") found components:  Interpreter 
-- Board: nrf52840dongle_nrf52840
-- Found toolchain: zephyr (/home/.../zephyr-sdk-0.11.2)
-- Found west: /home/.../.local/bin/west (found suitable version "0.7.2", minimum required is "0.7.1")
-- Found dtc: /home/.../zephyr-sdk-0.11.2/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.5.0", minimum required is "1.4.6")
-- Found BOARD.dts: /home/.../zephyrproject/zephyr/boards/arm/nrf52840dongle_nrf52840/nrf52840dongle_nrf52840.dts
-- Generated zephyr.dts: /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-zeta/build/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-zeta/build/zephyr/include/generated/devicetree_unfixed.h
Parsing /home/.../zephyrproject/zephyr/Kconfig
Loaded configuration '/home/.../zephyrproject/zephyr/boards/arm/nrf52840dongle_nrf52840/nrf52840dongle_nrf52840_defconfig'
Merged configuration '/home/.../zephyrproject/experimental_evaluation/sensors-over-internet-zeta/prj_nrf52840dongle_nrf52840.conf'
Merged configuration '/home/.../zephyrproject/experimental_evaluation/sensors-over-internet-zeta/build/zeta/zeta.conf'
Configuration saved to '/home/.../zephyrproject/experimental_evaluation/sensors-over-internet-zeta/build/zephyr/.config'
Kconfig header saved to '/home/.../zephyrproject/experimental_evaluation/sensors-over-internet-zeta/build/zephyr/include/generated/autoconf.h'
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/...//zephyr-sdk-0.11.2/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
-- Cache files will be written to: /home/.../.cache/zephyr
CMake Warning at /home/.../zephyrproject/zephyr/subsys/usb/CMakeLists.txt:28 (message):
  CONFIG_USB_DEVICE_VID has default value 0x2FE3.

  This value is only for testing and MUST be configured for USB products.


CMake Warning at /home/.../zephyrproject/zephyr/subsys/usb/CMakeLists.txt:34 (message):
  CONFIG_USB_DEVICE_PID has default value 0x100.

  This value is only for testing and MUST be configured for USB products.


[ZETA]: Set Zeta as a zephyr module
-- Configuring done
-- Generating done
-- Build files have been written to: /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-zeta/build
-- west build: building application
[1/163] Preparing syscall dependency handling

[158/163] Linking C executable zephyr/zephyr_prebuilt.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:       49792 B      1020 KB      4.77%
            SRAM:       25550 B       256 KB      9.75%
        IDT_LIST:          88 B         2 KB      4.30%
[163/163] Linking C executable zephyr/zephyr.elf
#+end_example
 
	For building this sample, we have to execute this to the Native Posix board:

	#+BEGIN_SRC bash
rm -rf build && west build -b native_posix
	#+END_SRC

	Expected results:
	#+begin_example
-- west build: generating a build system
[ZETA]: Running zeta.cmake
[ZETA]: Current dir = /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-<variation>
[ZETA]: ZETA_MODULE_DIR = /home/.../.local/lib/python3.6/site-packages/zeta
[ZETA]: PROJECT_DIR = /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-<variation>/build
[ZETA]: ZETA_DIR =  /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-<variation>/build/zeta
[ZETA]: ZETA_SRC_DIR = /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-<variation>/build/zeta/src
[ZETA]: ZETA_INCLUDE_DIR = /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-<variation>/build/zeta/include
[ZETA]: ZETA_TEMPLATES_DIR = /home/.../.local/lib/python3.6/site-packages/zeta/templates
[ZETA]: Creating Zeta project folder
[ZETA]: Generating zeta.h...[OK]
[ZETA]: Generating zeta.c...[OK]
[ZETA]: Generating zeta.conf...[OK]
Including boilerplate (Zephyr base): /home/.../zephyrproject/zephyr/cmake/app/boilerplate.cmake
-- Application: /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-<variation>
-- Zephyr version: 2.3.0-rc1 (/home/.../zephyrproject/zephyr)
-- Found Python3: /usr/bin/python3.6 (found suitable exact version "3.6.9") found components:  Interpreter 
-- Board: native_posix
-- Found toolchain: zephyr (/home/...//zephyr-sdk-0.11.2)
-- Found west: /home/.../.local/bin/west (found suitable version "0.7.2", minimum required is "0.7.1")
-- Found dtc: /home/.../zephyr-sdk-0.11.2/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.5.0", minimum required is "1.4.6")
-- Found toolchain: host (gcc/ld)
-- Found BOARD.dts: /home/.../zephyrproject/zephyr/boards/posix/native_posix/native_posix.dts
-- Generated zephyr.dts: /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-<variation>/build/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-<variation>/build/zephyr/include/generated/devicetree_unfixed.h
Parsing /home/.../zephyrproject/zephyr/Kconfig
Loaded configuration '/home/.../zephyrproject/zephyr/boards/posix/native_posix/native_posix_defconfig'
Merged configuration '/home/.../zephyrproject/experimental_evaluation/sensors-over-internet-<variation>/prj.conf'
Merged configuration '/home/.../zephyrproject/experimental_evaluation/sensors-over-internet-<variation>/build/zeta/zeta.conf'
Configuration saved to '/home/.../zephyrproject/experimental_evaluation/sensors-over-internet-<variation>/build/zephyr/.config'
Kconfig header saved to '/home/.../zephyrproject/experimental_evaluation/sensors-over-internet-<variation>/build/zephyr/include/generated/autoconf.h'
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/gcc
-- Cache files will be written to: /home/.../.cache/zephyr
[ZETA]: Set Zeta as a zephyr module
-- Configuring done
-- Generating done
-- Build files have been written to: /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-<variation>/build
-- west build: building application
[1/104] Preparing syscall dependency handling

[104/104] Linking C executable zephyr/zephyr.elf
	#+end_example

	For running it, you must to run the following command:
	#+BEGIN_SRC bash
west build -t run
	#+END_SRC

	Expected results:
#+begin_example
-- west build: running target run
[0/1] cd /home/.../zephyrproject/experimental_evaluation/sensors-over-internet-zeta/build ...drigopex/MEGA/Venus/Projects/zephyrproject/experimental_evaluation/sensors-over-internet-zeta/build/zephyr/zephyr.exe
 Booting Zephyr OS build v2.3.0-rc1-229-g56b65e43de85  ***
[00:00:00.000,000] <dbg> zeta.BOARD_task: BOARD Service has started...[OK]
[00:00:00.000,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:00.000,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:00.000,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:00.000,000] <inf> fs_nvs: 4 Sectors of 4096 bytes
[00:00:00.000,000] <inf> fs_nvs: alloc wra: 0, fe0
[00:00:00.000,000] <inf> fs_nvs: data wra: 0, 6
[00:00:00.000,000] <inf> zeta: NVS started...[OK]
[00:00:00.000,000] <inf> zeta: [ ] Recovering data from flash
[00:00:00.000,000] <inf> zeta: Id: 1
[00:00:00.000,000] <inf> zeta: Value: 
1e                                               |.                
[00:00:00.000,000] <inf> zeta: Id: 5
[00:00:00.000,000] <inf> zeta: Value: 
a2 8a 8c 01 00                                   |.....            
[00:00:00.000,000] <inf> zeta: [X] Recovering data from flash
[00:00:00.000,000] <dbg> zeta.CORE_task: CORE Service has started...[OK]
[00:00:00.000,000] <dbg> zeta.core_handle_channel_callback: Data received from sensor A: 30
[00:00:00.000,000] <dbg> zeta.core_handle_channel_callback: Data received from sensor B: 89
[00:00:00.000,000] <dbg> zeta.core_handle_channel_callback: Data received from sensor C: 101352
[00:00:00.000,000] <dbg> zeta.NET_task: NET Service has started...[OK]
[00:00:00.000,000] <dbg> zeta.handle_net_requests: Getting a virtual packet request from net with id: a0
[00:00:00.000,000] <dbg> zeta.handle_net_requests: Sending a net packet request to NET_REQUEST channel...
[00:00:00.000,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:00.000,000] <dbg> zeta.core_handle_channel_callback: Net request received with ID: a0
[00:00:00.000,000] <dbg> zeta.NET_service_callback: Calling NET Callback...
[00:00:03.010,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:03.010,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:03.010,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:03.010,000] <dbg> zeta.core_handle_channel_callback: Data received from sensor A: 22
[00:00:03.010,000] <dbg> zeta.core_handle_channel_callback: Data received from sensor B: 88
[00:00:03.010,000] <dbg> zeta.core_handle_channel_callback: Data received from sensor C: 101379
[00:00:06.020,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:06.020,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:06.020,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:06.020,000] <dbg> zeta.core_handle_channel_callback: Data received from sensor A: 23
[00:00:06.020,000] <dbg> zeta.core_handle_channel_callback: Data received from sensor B: 87
[00:00:06.020,000] <dbg> zeta.core_handle_channel_callback: Data received from sensor C: 101406
[00:00:09.030,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:09.030,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:09.030,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:09.030,000] <dbg> zeta.core_handle_channel_callback: Data received from sensor A: 24
[00:00:09.030,000] <dbg> zeta.core_handle_channel_callback: Data received from sensor B: 86
[00:00:09.030,000] <dbg> zeta.core_handle_channel_callback: Data received from sensor C: 101433
[00:00:10.010,000] <wrn> zeta: CPU usage: 30%
[00:00:10.010,000] <dbg> zeta.net_handle_channel_callback: Net response received: a0
[00:00:10.010,000] <dbg> zeta.net_handle_channel_callback: Last sensor A data saved: 30
[00:00:10.010,000] <dbg> zeta.handle_net_requests: Getting a virtual packet request from net with id: a4
[00:00:10.010,000] <dbg> zeta.handle_net_requests: Sending a net packet request to NET_REQUEST channel...
[00:00:10.010,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:10.010,000] <dbg> zeta.sensor_b_mean: B Mean -> i: 4, sum: 350, mean: 87
[00:00:10.010,000] <dbg> zeta.core_handle_channel_callback: Net request received with ID: a4
[00:00:10.010,000] <dbg> zeta.NET_service_callback: Calling NET Callback...
[00:00:12.040,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:12.040,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:12.040,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:12.040,000] <dbg> zeta.core_handle_channel_callback: Data received from sensor A: 25
[00:00:12.040,000] <dbg> zeta.core_handle_channel_callback: Data received from sensor B: 85
[00:00:12.040,000] <dbg> zeta.core_handle_channel_callback: Data received from sensor C: 101460
[00:00:15.050,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:15.050,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
[00:00:15.050,000] <dbg> zeta.CORE_service_callback: Calling CORE Callback...
#+end_example

You must type /Ctrl+c/ to stop execution.
